export const banner = [
  "http://117.6.133.148:8088/e-learning-01.jpg",
  "http://117.6.133.148:8088/blended-learning-01.jpg",
];

export const provinces = [
  {
    id: 0,
    name_ko: "전체",
    isAutonomous: null,
  },
  {
    id: 10,
    name_ko: "경기도",
    isAutonomous: false,
  },
  {
    id: 1,
    name_ko: "서울특별시",
    isAutonomous: false,
  },
  {
    id: 6,
    name_ko: "광주광역시",
    isAutonomous: false,
  },
  {
    id: 8,
    name_ko: "대구광역시",
    isAutonomous: false,
  },
  {
    id: 11,
    name_ko: "대전광역시",
    isAutonomous: false,
  },
  {
    id: 7,
    name_ko: "부산광역시",
    isAutonomous: false,
  },
  {
    id: 5,
    name_ko: "울산광역시",
    isAutonomous: false,
  },
  {
    id: 9,
    name_ko: "인천광역시",
    isAutonomous: false,
  },
  {
    id: 4,
    name_ko: "강원도",
    isAutonomous: false,
  },
  {
    id: 12,
    name_ko: "경상남도",
    isAutonomous: false,
  },
  {
    id: 13,
    name_ko: "경상북도",
    isAutonomous: false,
  },
  {
    id: 15,
    name_ko: "세종특별자치도",
    isAutonomous: true,
  },
  {
    id: 2,
    name_ko: "전라남도",
    isAutonomous: false,
  },
  {
    id: 3,
    name_ko: "전라북도",
    isAutonomous: false,
  },
  {
    id: 14,
    name_ko: "제주특별자치도",
    isAutonomous: false,
  },
  {
    id: 16,
    name_ko: "충청남도",
    isAutonomous: false,
  },
  {
    id: 17,
    name_ko: "충청북도",
    isAutonomous: false,
  },
];

export const listNew = [
  {
    id: 98,
    filed: null,
    content: "<p></p>",
    title: "Tin tức ngày 25 tháng 05 năm 2024",
    category: null,
    isActive: true,
    mainImage:
      "https://api.g1230.com/api/education/file/1714373228교육뉴스_썸네일.jpg",
    campus: {
      id: 92,
      name: "G1230FC",
      name_en: "FC",
      numberPhone: "1599-1230",
      address: "경기도 고양시 덕양구 화정동 970-2 케이탑리츠빌딩",
      avatar: "https://api.g1230.com/api/education/file/1683188968대문사진.jpg",
      nameAvatar: "1683188968대문사진.jpg",
      dateOfReg: 1668438000000,
      createdDate: 1668486585000,
      isActive: true,
      lat: "37.6325322",
      lng: "126.8305459",
      user: {
        id: 39,
        username: "admin",
        password: null,
        email: "online@g1230fc.com",
        firstName: null,
        lastName: null,
        fullName: "관리자",
        age: null,
        idNumber: "266cc8fc-2a04-4d3d-806d-e63cf213c10d",
        address: null,
        birthDate: null,
        isActive: true,
        createdDate: 1669240279000,
        roleName: "Super Admin",
        fullRole: "ROLE_SUPER_ADMIN",
        campusName: "G1230FC",
        phone: "010-0000-0000",
      },
      commune: {
        id: 2423,
        name_ko: "화정동",
        districtDto: {
          id: 123,
          name_ko: "고양시 덕양구",
          provinceDto: {
            id: 10,
            name_ko: "경기도",
            isAutonomous: false,
          },
        },
        provinceDto: {
          id: 10,
          name_ko: "경기도",
          isAutonomous: false,
        },
      },
      centerCampus: true,
      busAnnouncement: "",
      provinceName: "경기도",
    },
    file: null,
    fileDtos: null,
    files: null,
    next: null,
    previous: null,
    createDate: "2024-04-29",
    totalViews: 40,
    contentHtml: null,
  },
  {
    id: 97,
    filed: null,
    content: "<p></p>",
    title: "Tin tức ngày 24 tháng 05 năm 2024",
    category: null,
    isActive: true,
    mainImage:
      "https://api.g1230.com/api/education/file/1711933732교육뉴스_썸네일.jpg",
    campus: {
      id: 92,
      name: "G1230FC",
      name_en: "FC",
      numberPhone: "1599-1230",
      address: "경기도 고양시 덕양구 화정동 970-2 케이탑리츠빌딩",
      avatar: "https://api.g1230.com/api/education/file/1683188968대문사진.jpg",
      nameAvatar: "1683188968대문사진.jpg",
      dateOfReg: 1668438000000,
      createdDate: 1668486585000,
      isActive: true,
      lat: "37.6325322",
      lng: "126.8305459",
      user: {
        id: 39,
        username: "admin",
        password: null,
        email: "online@g1230fc.com",
        firstName: null,
        lastName: null,
        fullName: "관리자",
        age: null,
        idNumber: "266cc8fc-2a04-4d3d-806d-e63cf213c10d",
        address: null,
        birthDate: null,
        isActive: true,
        createdDate: 1669240279000,
        roleName: "Super Admin",
        fullRole: "ROLE_SUPER_ADMIN",
        campusName: "G1230FC",
        phone: "010-0000-0000",
      },
      commune: {
        id: 2423,
        name_ko: "화정동",
        districtDto: {
          id: 123,
          name_ko: "고양시 덕양구",
          provinceDto: {
            id: 10,
            name_ko: "경기도",
            isAutonomous: false,
          },
        },
        provinceDto: {
          id: 10,
          name_ko: "경기도",
          isAutonomous: false,
        },
      },
      centerCampus: true,
      busAnnouncement: "",
      provinceName: "경기도",
    },
    file: null,
    fileDtos: null,
    files: null,
    next: null,
    previous: null,
    createDate: "2024-04-01",
    totalViews: 34,
    contentHtml: null,
  },
  {
    id: 96,
    filed: null,
    content:
      "<h2><strong>Tóm tắt tin tức </strong></h2><p></p><p></p><p><br></p><h2><strong>một năm đẹp</strong></h2><p></p><p></p><p><br></p><h3><strong>1234567.</strong></h3><h3><strong></strong></h3>",
    title: "Tin tức năm 2024",
    category: null,
    isActive: true,
    mainImage:
      "https://api.g1230.com/api/education/file/1709183320교육뉴스_썸네일.jpg",
    campus: {
      id: 92,
      name: "G1230FC",
      name_en: "FC",
      numberPhone: "1599-1230",
      address: "경기도 고양시 덕양구 화정동 970-2 케이탑리츠빌딩",
      avatar: "https://api.g1230.com/api/education/file/1683188968대문사진.jpg",
      nameAvatar: "1683188968대문사진.jpg",
      dateOfReg: 1668438000000,
      createdDate: 1668486585000,
      isActive: true,
      lat: "37.6325322",
      lng: "126.8305459",
      user: {
        id: 39,
        username: "admin",
        password: null,
        email: "online@g1230fc.com",
        firstName: null,
        lastName: null,
        fullName: "관리자",
        age: null,
        idNumber: "266cc8fc-2a04-4d3d-806d-e63cf213c10d",
        address: null,
        birthDate: null,
        isActive: true,
        createdDate: 1669240279000,
        roleName: "Super Admin",
        fullRole: "ROLE_SUPER_ADMIN",
        campusName: "G1230FC",
        phone: "010-0000-0000",
      },
      commune: {
        id: 2423,
        name_ko: "화정동",
        districtDto: {
          id: 123,
          name_ko: "고양시 덕양구",
          provinceDto: {
            id: 10,
            name_ko: "경기도",
            isAutonomous: false,
          },
        },
        provinceDto: {
          id: 10,
          name_ko: "경기도",
          isAutonomous: false,
        },
      },
      centerCampus: true,
      busAnnouncement: "",
      provinceName: "경기도",
    },
    file: null,
    fileDtos: null,
    files: null,
    next: null,
    previous: null,
    createDate: "2024-02-29",
    totalViews: 56,
    contentHtml: null,
  },
  {
    id: 95,
    filed: null,
    content: '<p class="ql-align-center"></p>',
    title: "Ngày 25 tháng 05",
    category: null,
    isActive: true,
    mainImage:
      "https://api.g1230.com/api/education/file/1709183320교육뉴스_썸네일.jpg",
    campus: {
      id: 92,
      name: "G1230FC",
      name_en: "FC",
      numberPhone: "1599-1230",
      address: "경기도 고양시 덕양구 화정동 970-2 케이탑리츠빌딩",
      avatar: "https://api.g1230.com/api/education/file/1683188968대문사진.jpg",
      nameAvatar: "1683188968대문사진.jpg",
      dateOfReg: 1668438000000,
      createdDate: 1668486585000,
      isActive: true,
      lat: "37.6325322",
      lng: "126.8305459",
      user: {
        id: 39,
        username: "admin",
        password: null,
        email: "online@g1230fc.com",
        firstName: null,
        lastName: null,
        fullName: "관리자",
        age: null,
        idNumber: "266cc8fc-2a04-4d3d-806d-e63cf213c10d",
        address: null,
        birthDate: null,
        isActive: true,
        createdDate: 1669240279000,
        roleName: "Super Admin",
        fullRole: "ROLE_SUPER_ADMIN",
        campusName: "G1230FC",
        phone: "010-0000-0000",
      },
      commune: {
        id: 2423,
        name_ko: "화정동",
        districtDto: {
          id: 123,
          name_ko: "고양시 덕양구",
          provinceDto: {
            id: 10,
            name_ko: "경기도",
            isAutonomous: false,
          },
        },
        provinceDto: {
          id: 10,
          name_ko: "경기도",
          isAutonomous: false,
        },
      },
      centerCampus: true,
      busAnnouncement: "",
      provinceName: "경기도",
    },
    file: null,
    fileDtos: null,
    files: null,
    next: null,
    previous: null,
    createDate: "2024-02-29",
    totalViews: 41,
    contentHtml: null,
  },
];

export const listFeedBack = [
  {
    id: 18,
    title: "에스라이팅 동백캠퍼스 이야기",
    nameStudent: "Nguyễn Văn A",
    content:
      '<p class="ql-align-center"><br></p><p class="ql-align-center"><br></p><p class="ql-align-center"><br></p><p class="ql-align-center"></p><p class="ql-align-center"><br></p><p class="ql-align-center"></p><p><br></p><p><br></p><p><br></p><p><br></p><h1>“부족한 만큼 채우고 갈 수 있는 학원”</h1><p>&nbsp;</p><h3>CTEG 이벤트 1등이라는 상을 받고 인터뷰를 진행하며, 처음 시작했을 때를 떠올려보게 되네요.</h3><h3>&nbsp;학원을 경영하며 제 꿈을 실현시키고 성장할 수 있었던 건. 딱 두 가지를 선택하라고 하면 처음부터 지금까지 변함없이 함께 해주신 한 분 한 분의 선생님들과 정말 언제나 한결같이 믿고 맡겨주신 학부모님들이 계셨기에 가능했던 것 같아요. 이 시간을 통해서 우리 샘들과 에스라이팅 동백 캠퍼스 부모님 그리고 또 샘들의 열정과 부모님들 관심이 하나가 되어 관리 잘되고 아주 깐깐하다고 소문난 우리 학원에서 잘 버텨주고 따라와 주고 있는 우리 친구들에게 원장님이 너무나 고맙다고 전하고 싶습니다. 그리고 탄탄한 실력으로 졸업해서 상급학교에서 각자의 실력을 잘 발휘해주고 있는 우리 졸업생 친구들에게도 이 자리를 통해서 고맙다고 전하고 싶습니다.</h3><h3>&nbsp;</h3><h3>&nbsp;사실 이 모든 것을 또 가능하게 도와준 건 무엇보다 제가 꼼꼼하게 보고 선택했던 에스라이팅 프로그램이라는 도구가 있었기 때문인 것 같습니다. 4가지 영역의 교재가 하나의 주제로 연결되어 있어서 요즘 우리나라 교육이 추구하고 있는 주제 중심 통합수업과 방향이 너무나 잘 맞아요. 저레벨 교재는 기초를 다지기에 최적화되어 있고 고레벨로 올라갈수록 다져진 실력이 빛이 날 수 있도록 잘 구성이 되어있는 것 같습니다. 무엇보다 문법 교재 라인은 시중교재가 따라 갈 수 없죠. 정말 딱 제 스타일입니다. 명확한 개념 설명, 연습문제와 실전 문제까지 너무 간결하고 군더더기 없게 만들어져 있어서 현장에 있는 샘들과 늘 감탄을 하곤 합니다. 그러고 보니 좋은 프로그램을 만난 게 행운이었네요.</h3><h3>&nbsp;</h3><h3>&nbsp;저희 학원 컨셉은 “가족 같은 분위기”입니다. 일단 함께 시작하면 내 아이처럼 사랑이 우선이 되어요. 그리고 부족한 부분은 지나가지 않고 한 명 한 명 채우려고 무지 애씁니다. 잘하는 친구들은 더 많이 펼칠 수 있도록 확장시켜 주고요. 보통 등원을 시작하면 졸업할 때까지 다니는 친구들이 90% 이상이 되어서 가족처럼 되는 것 같기도 해요(웃음). 성장기의 감정 기복까지 끌어안고 저희와 함께 보내고 있으니까요(웃음). 저희 원은 아직도 성장 중입니다. 저는 욕심 내지 않고 지금처럼 진심으로 최선을 다 할 겁니다. 또 한 한반 한반을 내 자식처럼 이끌어 주시는 우리 쌤들에게도 보람되고 행복한 일터가 되도록 노력할 겁니다. 감사합니다.</h3><h3>&nbsp;</h3><h3>&nbsp;</h3><p><br></p>',
    campus: {
      id: 92,
      name: "G1230FC",
      name_en: "FC",
      numberPhone: "1599-1230",
      address: "경기도 고양시 덕양구 화정동 970-2 케이탑리츠빌딩",
      avatar: "https://api.g1230.com/api/education/file/1683188968대문사진.jpg",
      nameAvatar: "1683188968대문사진.jpg",
      dateOfReg: 1668438000000,
      createdDate: 1668486585000,
      isActive: true,
      lat: "37.6325322",
      lng: "126.8305459",
      user: {
        id: 39,
        username: "admin",
        password: null,
        email: "online@g1230fc.com",
        firstName: null,
        lastName: null,
        fullName: "관리자",
        age: null,
        idNumber: "266cc8fc-2a04-4d3d-806d-e63cf213c10d",
        address: null,
        birthDate: null,
        isActive: true,
        createdDate: 1669240279000,
        roleName: "Super Admin",
        fullRole: "ROLE_SUPER_ADMIN",
        campusName: "G1230FC",
        phone: "010-0000-0000",
      },
      commune: {
        id: 2423,
        name_ko: "화정동",
        districtDto: {
          id: 123,
          name_ko: "고양시 덕양구",
          provinceDto: {
            id: 10,
            name_ko: "경기도",
            isAutonomous: false,
          },
        },
        provinceDto: {
          id: 10,
          name_ko: "경기도",
          isAutonomous: false,
        },
      },
      centerCampus: true,
      busAnnouncement: "",
      provinceName: "경기도",
    },
    mainImage: "https://api.g1230.com/api/education/file/1669965749그림2.jpg",
    nameImage: null,
    next: null,
    previous: null,
    totalViews: 274,
    dateOfReg: 1669906800000,
    contentNotHtml:
      "“Từ khi có hệ sinh thái học tập điểm số của em đã được cải thiện ...",
    createDate: "2022-12-02",
  },
  {
    id: 15,
    title: "에스라이팅 논현캠퍼스 이야기",
    nameStudent: "Nguyễn Văn B",
    content:
      '<h2 class="ql-align-center"><br></h2><p class="ql-align-center"></p><h2 class="ql-align-center"><br></h2><h1 class="ql-align-center"><span style="color: rgb(68, 68, 68);">｜</span>에스라이팅 논현캠퍼스 이야기</h1><p class="ql-align-center"><br></p><h3 class="ql-align-center"><span style="color: black;">에스라이팅 어학원은 시대에 맞는 어학원입니다.</span></h3><h3 class="ql-align-center"><span style="color: black;">에스라이팅 어학원은 이 자체가 수행 평가를 완벽하게 준비할 수 있어요. </span></h3><h3 class="ql-align-center"><span style="color: black;">왜냐하면 수행평가에 Writing이 있죠, Speaking이 있죠. Listening이 있고 포트폴리오가 있잖아요. </span></h3><h3 class="ql-align-center"><span style="color: black;">이게 우리 하는 수업이잖아요.</span></h3><h3 class="ql-align-center"><br></h3><h3 class="ql-align-center"><span style="color: black;">그 중에 지필고사가 이제 중간고사 25점, 기말고사 25점, 수행평가가 50점이에요. </span></h3><h3 class="ql-align-center"><span style="color: black;">근데 50점 안에 Witing이 20점이에요. 지필 고사하고 맞먹어요. </span></h3><h3 class="ql-align-center"><br></h3><h3 class="ql-align-center"><span style="color: black;">근데 이 수행평가 Witing 20점을, </span></h3><h3 class="ql-align-center"><span style="color: black;">수업시간에 선생님이 칠판에 문제를 써줬을 때, Writing을 하지 않던 학생들은 핸드폰 보고있어요. </span></h3><h3 class="ql-align-center"><span style="color: black;">영어로 쓰라는데 저게 뭐야 그러고 있는데 에스라이팅 어학원 다니는 애들은 글을 써요. 진짜 쓰고 있어요. </span></h3><h3 class="ql-align-center"><span style="color: black;">40분을 주면 열심히 쓰고 있죠. 전부 다 A+에요. 중요한 건 수행평가 20점 만점이 중간고사하고 맞먹잖아요.</span></h3><h3 class="ql-align-center"><br></h3><h3 class="ql-align-center"><span style="color: black;">지금 이제 우리 원장님들이 특히 영어 잘 몰라서 엄청 고생하고 계신거에요. </span></h3><h3 class="ql-align-center"><span style="color: black;">본인들이 막 뭘 열심히 만들어 보고 뭘 해보려고 하잖아요. </span></h3><h3 class="ql-align-center"><span style="color: black;">그게 아니라 본사에서 제공하는 것을 잘 쓰면 돼요.&nbsp;&nbsp;</span></h3><h3 class="ql-align-center"><span style="color: black;">내신기간 때도 내신준비 완벽하게 준비하게 자료가 돼 있고, 수행평가도 완벽하게 준비할 수 있도록 프로그램이 되어 있죠. </span></h3><h3 class="ql-align-center"><span style="color: black;">주관식 시험도 잡아줄 수 있고 얼마나 편해요. 그래서 이 두가지 잘해가면 아이들 확실하게 잡아줄 수 있어요.</span></h3><h3 class="ql-align-center"><span style="color: black;">에스라이팅, 반드시 하셔야 합니다. </span></h3><p class="ql-align-center"><br></p><p class="ql-align-center"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><br></p><p class="ql-align-center"><span style="color: black;">&nbsp;</span></p>',
    campus: {
      id: 92,
      name: "G1230FC",
      name_en: "FC",
      numberPhone: "1599-1230",
      address: "경기도 고양시 덕양구 화정동 970-2 케이탑리츠빌딩",
      avatar: "https://api.g1230.com/api/education/file/1683188968대문사진.jpg",
      nameAvatar: "1683188968대문사진.jpg",
      dateOfReg: 1668438000000,
      createdDate: 1668486585000,
      isActive: true,
      lat: "37.6325322",
      lng: "126.8305459",
      user: {
        id: 39,
        username: "admin",
        password: null,
        email: "online@g1230fc.com",
        firstName: null,
        lastName: null,
        fullName: "관리자",
        age: null,
        idNumber: "266cc8fc-2a04-4d3d-806d-e63cf213c10d",
        address: null,
        birthDate: null,
        isActive: true,
        createdDate: 1669240279000,
        roleName: "Super Admin",
        fullRole: "ROLE_SUPER_ADMIN",
        campusName: "G1230FC",
        phone: "010-0000-0000",
      },
      commune: {
        id: 2423,
        name_ko: "화정동",
        districtDto: {
          id: 123,
          name_ko: "고양시 덕양구",
          provinceDto: {
            id: 10,
            name_ko: "경기도",
            isAutonomous: false,
          },
        },
        provinceDto: {
          id: 10,
          name_ko: "경기도",
          isAutonomous: false,
        },
      },
      centerCampus: true,
      busAnnouncement: "",
      provinceName: "경기도",
    },
    mainImage: "https://api.g1230.com/api/education/file/1669790960그림1.jpg",
    nameImage: null,
    next: null,
    previous: null,
    totalViews: 267,
    dateOfReg: 1669906800000,
    contentNotHtml:
        "“Từ khi có hệ sinh thái học tập điểm số của em đã được cải thiện ...",
    createDate: "2022-11-30",
  },
  {
    id: 12,
    title: "G1230수학 가오캠퍼스 이야기: 가오마을 창의축제",
    nameStudent: "Mai Tiến A",
    content:
      '<p class="ql-align-center"><br></p><p class="ql-align-center"></p><p class="ql-align-center"><br></p><h1 class="ql-align-center"><span style="color: rgb(68, 68, 68);">｜가오캠퍼스 이야기: 가오마을 창의축제</span></h1><p class="ql-align-center"><br></p><h3 class="ql-align-center"><span style="color: black;">교육적으로 너무 열악한 지구에 우리 아이들에게 교육적인 혜택이 없어서 속상했어요. </span></h3><h3 class="ql-align-center"><span style="color: black;">여기사는 우리는 너무 억울하지 않냐, 그럼 우리끼리 해보자 해서 시작한 행사였어요. </span></h3><h3 class="ql-align-center"><span style="color: black;">재작년인가 행사를 저희 단독으로 했었는데 너무 재미있었어요. </span></h3><h3 class="ql-align-center"><span style="color: black;">어떤 체험할지 구성원이 구상을 하고 아이들도 프로그램을 공모하고 그렇게 해서 행사 내용을 꾸렸어요. </span></h3><h3 class="ql-align-center"><br></h3><h3 class="ql-align-center"><span style="color: black;">근데 사실, 야외에서 하는 건데 저희만 하기에는 너무 학원 홍보라고 색안경 끼는 분들이 있을까 봐 일부러 학원 이야기는 숨겨두었어요. </span></h3><h3 class="ql-align-center"><span style="color: black;">근데 오셔서 많이들 물어보긴 해요. 어디서 하는 거냐고. G1230이라는 게 딱 수학 이름 같지는 않잖아요. </span></h3><h3 class="ql-align-center"><span style="color: black;">아이들이 동네에다 행사 홍보를 붙여놓았을 때, 그렇게 학원도 알리게 되는 것 같아요.</span></h3><h3 class="ql-align-center"><br></h3><h3 class="ql-align-center"><span style="color: black;">“배워서 남준다”</span></h3><h3 class="ql-align-center"><br></h3><h3 class="ql-align-center"><span style="color: black;">배워서 남준다 라는 것이 저희의 모토거든요. </span></h3><h3 class="ql-align-center"><span style="color: black;">우리 학원에서 배운 아이들이 지역사회에 나가서 봉사하고 헌신하고 배움을 나눠줄 수 있다면 감사하죠. </span></h3><h3 class="ql-align-center"><span style="color: black;">수학으로 즐거움을 찾게 해주는 것, 수학을 꿈꾸는 아이들, 수학으로 재미를 찾는 아이들, 이런 것들을 지역사회의 많은 사람들에게 보여주고 싶었어요. </span></h3><h3 class="ql-align-center"><span style="color: black;">아이들 다니는 학원은 ‘공부’ 이런 느낌이 아니고 학습을 자연스럽게 익힐 수 있는 공간이었으면 해요. </span></h3><h3 class="ql-align-center"><span style="color: black;">배울 땐 배우고, 실천할 땐 실천하고, 꿈을 키워가고 지역사회에 헌신하는 시민의식을 가진 아이들로 키우고 싶어요. </span></h3><h3 class="ql-align-center"><span style="color: black;">그게 저와 우리 선생님들의 목표입니다.</span></h3><h3 class="ql-align-center"><br></h3><h3 class="ql-align-center"><span style="color: black;">오늘은 이렇게 수학, 창의 체험으로만 구성이 되었지만 앞으로는 그 규모를 더 키우고 싶어요. </span></h3><h3 class="ql-align-center"><span style="color: black;">다른 분들이랑도 연계해서 버스킹도 하고, 더 다양한 체험을 하고, 앞으로는 가오동 마을축제로 청소년축제로 성장시키고 싶어요. </span></h3><h3 class="ql-align-center"><span style="color: black;">그리고 이런 행사들이, 저희의 취지들이 알려지면 가오동의 이야기로만 남지 않고 많은 분들이 각 지역으로 가지고 나갔으면 좋겠어요.</span></h3><p class="ql-align-center"><br></p><p class="ql-align-center"><br></p><p class="ql-align-center"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><span style="color: black;">&nbsp;</span></p>',
    campus: {
      id: 92,
      name: "G1230FC",
      name_en: "FC",
      numberPhone: "1599-1230",
      address: "경기도 고양시 덕양구 화정동 970-2 케이탑리츠빌딩",
      avatar: "https://api.g1230.com/api/education/file/1683188968대문사진.jpg",
      nameAvatar: "1683188968대문사진.jpg",
      dateOfReg: 1668438000000,
      createdDate: 1668486585000,
      isActive: true,
      lat: "37.6325322",
      lng: "126.8305459",
      user: {
        id: 39,
        username: "admin",
        password: null,
        email: "online@g1230fc.com",
        firstName: null,
        lastName: null,
        fullName: "관리자",
        age: null,
        idNumber: "266cc8fc-2a04-4d3d-806d-e63cf213c10d",
        address: null,
        birthDate: null,
        isActive: true,
        createdDate: 1669240279000,
        roleName: "Super Admin",
        fullRole: "ROLE_SUPER_ADMIN",
        campusName: "G1230FC",
        phone: "010-0000-0000",
      },
      commune: {
        id: 2423,
        name_ko: "화정동",
        districtDto: {
          id: 123,
          name_ko: "고양시 덕양구",
          provinceDto: {
            id: 10,
            name_ko: "경기도",
            isAutonomous: false,
          },
        },
        provinceDto: {
          id: 10,
          name_ko: "경기도",
          isAutonomous: false,
        },
      },
      centerCampus: true,
      busAnnouncement: "",
      provinceName: "경기도",
    },
    mainImage: "https://api.g1230.com/api/education/file/1669171537그림3.jpg",
    nameImage: null,
    next: null,
    previous: null,
    totalViews: 296,
    dateOfReg: 1669906800000,
    contentNotHtml:
      "“Từ khi có hệ sinh thái học tập điểm số của em đã được cải thiện ...",
    createDate: "2022-11-22",
  },
];
